name: Python Test Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12.6] # You can add multiple versions if needed.

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to the latest version

      - name: Set up Python
        uses: actions/setup-python@v4 # Updated to the latest version
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set environment variables
        run: |
          echo "BEARER_TOKEN=${{ secrets.BEARER_TOKEN }}" >> $GITHUB_ENV
          echo "BASIC_AUTH=${{ secrets.BASIC_AUTH }}" >> $GITHUB_ENV
          echo "FOLDER_ID=${{ secrets.FOLDER_ID }}" >> $GITHUB_ENV
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> $GITHUB_ENV
          echo "API_URL=${{ secrets.API_URL }}" >> $GITHUB_ENV

      - name: Run Python tests
        run: |
          python main.py
